# This file was generated by GoReleaser. DO NOT EDIT.
cask "clockify2cats" do
  version "3.4.1"

  on_macos do
    on_intel do
      sha256 "d074b0eb9267d1dc9a2d88af0a854198dd8783ac03c9d1a59fbbf0c6e90c1a02"
      url "https://github.com/marvincaspar/clockify2cats/releases/download/#{version}/clockify2cats_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "fa3a65a6822e1474624f1b9e33fec89cb8e325969a75f8d6621db10a1670bed2"
      url "https://github.com/marvincaspar/clockify2cats/releases/download/#{version}/clockify2cats_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3fd731c5c1f78f55ffa2f4b7da28ddc2ff858a241dd04edee20fe81ee156159e"
      url "https://github.com/marvincaspar/clockify2cats/releases/download/#{version}/clockify2cats_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3f8591c2d1ab39e1bf27d1f2283f0b16224c30e68c90efac75d87e8ce1e8cb29"
      url "https://github.com/marvincaspar/clockify2cats/releases/download/#{version}/clockify2cats_Linux_arm64.tar.gz"
    end
  end

  name "clockify2cats"
  desc "CLI for exporting clockify data and generate a SAP CATS report as csv"
  homepage "https://github.com/marvincaspar/clockify2cats"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clockify2cats"
  generate_completions_from_executable "clockify2cats",
    shell_parameter_format: :cobra

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/clockify2cats"]
    end
  end

  # No zap stanza required

end
