# This file was generated by GoReleaser. DO NOT EDIT.
cask "clockify2cats" do
  version "3.4.1"

  on_macos do
    on_intel do
      sha256 "fb8924224c628396bc8f61777b7dd29d97b1fc294411d0229f60cfb5cc6b3dd0"
      url "https://github.com/marvincaspar/clockify2cats/releases/download/#{version}/clockify2cats_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c9a6ecaf8ebed7728c067de651f726c2d69253054f04dcbe3bf5f91fcc344b3b"
      url "https://github.com/marvincaspar/clockify2cats/releases/download/#{version}/clockify2cats_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3d2a1cb5d3483e7a086b871f5ea7eee5cfd2d16bad25afe96304e8158e67fdef"
      url "https://github.com/marvincaspar/clockify2cats/releases/download/#{version}/clockify2cats_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "cbb3e6f3444b2ab840078a7e96386a02ec8d709c9bb2109d142160c674235bea"
      url "https://github.com/marvincaspar/clockify2cats/releases/download/#{version}/clockify2cats_Linux_arm64.tar.gz"
    end
  end

  name "clockify2cats"
  desc "CLI for exporting clockify data and generate a SAP CATS report as csv"
  homepage "https://github.com/marvincaspar/clockify2cats"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clockify2cats"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/clockify2cats"]
    end
  end

  generate_completions_from_executable "clockify2cats",
    shell_parameter_format: :cobra

  # No zap stanza required

end
