# This file was generated by GoReleaser. DO NOT EDIT.
cask "clockify2cats" do
  version "3.4.1"

  on_macos do
    on_intel do
      sha256 "a706fea84502f934d16f797e5d0dc3765f9191d6151319eedeca1dfecc295ce4"
      url "https://github.com/marvincaspar/clockify2cats/releases/download/#{version}/clockify2cats_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d3388782799b56e1bf6a510dd6dfc8be3153d15b34211d39478745e67bed33eb"
      url "https://github.com/marvincaspar/clockify2cats/releases/download/#{version}/clockify2cats_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ddbdfedb41b30953f24bf08af3ad844492393033b3f53eebf1897d5e902dbf0d"
      url "https://github.com/marvincaspar/clockify2cats/releases/download/#{version}/clockify2cats_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8aa8021a51336d9bd2359c648f1d8a7973c9afe163c422cd8104eb5eb2632ce9"
      url "https://github.com/marvincaspar/clockify2cats/releases/download/#{version}/clockify2cats_Linux_arm64.tar.gz"
    end
  end

  name "clockify2cats"
  desc "CLI for exporting clockify data and generate a SAP CATS report as csv"
  homepage "https://github.com/marvincaspar/clockify2cats"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clockify2cats"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/clockify2cats"]
    end
  end
  
  generate_completions_from_executable "clockify2cats",
    shell_parameter_format: :cobra

  # No zap stanza required

end
