# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clockify2cats < Formula
  desc ""
  homepage "https://github.com/marvincaspar/clockify2cats"
  version "3.2.0"

  on_macos do
    on_intel do
      url "https://github.com/marvincaspar/clockify2cats/releases/download/3.2.0/clockify2cats_Darwin_x86_64.tar.gz"
      sha256 "6cb1e39d06eb29b8f4eee055c14b0a5dc7731c7a41217a05dd291077073d5440"

      def install
        bin.install "clockify2cats"
      end
    end
    on_arm do
      url "https://github.com/marvincaspar/clockify2cats/releases/download/3.2.0/clockify2cats_Darwin_arm64.tar.gz"
      sha256 "4d9af006aa46ecf65ccf9bf2a102a342b946372c904d97403938f57e065ecd97"

      def install
        bin.install "clockify2cats"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marvincaspar/clockify2cats/releases/download/3.2.0/clockify2cats_Linux_x86_64.tar.gz"
        sha256 "ae5ade9b0598825b19270d75d6dda60243de8a41147b116299a64bc12a94f54c"

        def install
          bin.install "clockify2cats"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marvincaspar/clockify2cats/releases/download/3.2.0/clockify2cats_Linux_arm64.tar.gz"
        sha256 "ac4c620d163e60e045817caa32d8a704487266b4f925c1d282dd3d840978b272"

        def install
          bin.install "clockify2cats"
        end
      end
    end
  end

  test do
    system "#{bin}/clockify2cats version"
  end
end
