# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clockify2cats < Formula
  desc ""
  homepage "https://github.com/marvincaspar/clockify2cats"
  version "3.2.2"

  on_macos do
    on_intel do
      url "https://github.com/marvincaspar/clockify2cats/releases/download/3.2.2/clockify2cats_Darwin_x86_64.tar.gz"
      sha256 "28b14506617eb25d74d3713cac18174969054146d8a4f55fa0c72d127eb2e8ea"

      def install
        bin.install "clockify2cats"
      end
    end
    on_arm do
      url "https://github.com/marvincaspar/clockify2cats/releases/download/3.2.2/clockify2cats_Darwin_arm64.tar.gz"
      sha256 "62668eb38a8af8c11d6a3790b398039cd5db809419199db5a6a8d9acd26d8fd0"

      def install
        bin.install "clockify2cats"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marvincaspar/clockify2cats/releases/download/3.2.2/clockify2cats_Linux_x86_64.tar.gz"
        sha256 "9e18cc80e34e657b9a2c789a821fd7debbd39bb81a3446875d99212e885c1b6a"

        def install
          bin.install "clockify2cats"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marvincaspar/clockify2cats/releases/download/3.2.2/clockify2cats_Linux_arm64.tar.gz"
        sha256 "0d84550c59434a4f3dfde7cbe419ec6734d188d5ab1d80d4be23ec7b7aa8d67e"

        def install
          bin.install "clockify2cats"
        end
      end
    end
  end

  test do
    system "#{bin}/clockify2cats version"
  end
end
