# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clockify2cats < Formula
  desc ""
  homepage "https://github.com/marvincaspar/clockify2cats"
  version "3.2.1"

  on_macos do
    on_intel do
      url "https://github.com/marvincaspar/clockify2cats/releases/download/3.2.1/clockify2cats_Darwin_x86_64.tar.gz"
      sha256 "f52f0555d1e70e5922d78fb96f02beecebc68d17e32e9fcc54a5a29865c68d6f"

      def install
        bin.install "clockify2cats"
      end
    end
    on_arm do
      url "https://github.com/marvincaspar/clockify2cats/releases/download/3.2.1/clockify2cats_Darwin_arm64.tar.gz"
      sha256 "b3d5521e59d35a309ac7d17f7a9904d5445d4fd11b2946b29e692d02ed253475"

      def install
        bin.install "clockify2cats"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marvincaspar/clockify2cats/releases/download/3.2.1/clockify2cats_Linux_x86_64.tar.gz"
        sha256 "4cc0534fa1e4a71ebbd0106d54cf62a5d667e9bb0de0c2146b6381ef8330dbb2"

        def install
          bin.install "clockify2cats"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marvincaspar/clockify2cats/releases/download/3.2.1/clockify2cats_Linux_arm64.tar.gz"
        sha256 "e00efb51be70fe4c842fcbadcfacb7d6b92ea6ae1e1bc045d9732743b0e990e5"

        def install
          bin.install "clockify2cats"
        end
      end
    end
  end

  test do
    system "#{bin}/clockify2cats version"
  end
end
